### ISSUE TITLE
data_dir not working

### ISSUE THREAD

**Issue by georgpfolz** [nakagami/Products.ZSQLiteDA#2]
In Zope 4 and 5, it does not find the database files. Here is a fix that works for me:

```
import App.ApplicationManager
instancepath = App.ApplicationManager.getConfiguration().instancehome
data_dir=os.path.abspath(os.path.join(instancepath, 'var', 'sqlite'))
```

By the way, it would be nice to be able to configure (override) the data_dir so that it could even be outside the Zope instance. I'm thinking about a property on the ZSQLDA object.

**Comment by nakagami** [comment]
Can you make that fix a pull request?
If you send it, I'll probably merge it.

For a long time I thought it was a good idea to keep files outside of a Zope instance, but I don't think it's a good idea to have access to arbitrary files, so I'd appreciate suggestions on how to set it up.

**Comment by georgpfolz** [comment]
OK, I made the pull request :) 

> For a long time I thought it was a good idea to access a file outside of a Zope instance.
> But wouldn't it be a security risk if someone could specify any file?

I don't think just setting a path to an directory outside the Zope instance is a security risk. It's also done in the MailHost product, where you have to specify the spooler directory.

![Uploading Bildschirmfoto 2020-11-13 um 10.05.17.png…]()

**Comment by nakagami** [comment]
thanks for pull request #4 !

**Comment by nakagami** [comment]
The issue's main topic has been resolved, so this issue is now closed

**Comment by georgpfolz** [comment]
I'm nearly finished making a version of ZSQLiteDA with the possibility to use directories outside the Zope instance. I really need this, as I have some databases I use across several instances. Currently I use hardlinks to manage them, but this is unnecessarily complicated.

> For a long time I thought it was a good idea to access a file outside of a Zope instance. But wouldn't it be a security risk if someone could specify any file?

I have thought about the security concerns and I think that one should not provide the possibility to create directories and files outside the Zope instance (even if other products allow this).

I don't really see a big risk if someone can specify any file: that person must already have access to the ZMI and have the rights to change the database adapter. As far as I understand, one could specify a file but if it's not a sqlite file, it would not be readable with the DA. Also, one would have to know the exact location on the server of a sqlite file he would try to fraudulently access and it must be accessible with the rights of the user running the Zope instance (which hopefully ist not root).

So I made the following compromise: 
- database files outside the Zope instance have to be created on the file system before one can use them in the DA
- if the default path (_instance/var/sqlite_) is not present, it will be created automatically
- inside _instance/var/sqlite_ one can even create new database files from the ZMI (no big harm can come from that, I think. Even if one creates a lot of them, they are just empty files ad thus very small).

What do you think about it? Would you be ok with it?

Pull request coming soon!
