### ISSUE TITLE
browse tab

### ISSUE THREAD

**Issue by georgpfolz** [nakagami/Products.ZSQLiteDA#3]
I dearly miss the browse tab. 

So, although this version works with my Zope instance (Zope 5 currently) after patching the data_dir code, I'm reverting to an older one version I patched myself some months ago. 

Are there any plans to reinstate the browse-feature?

**Comment by nakagami** [comment]
Version 0.6.1 had a browse tab, but when running 0.7.0 on Zope 5, I removed it because I didn't think anyone would use it.

It would be nice if someone could revive the browse tab from the 0.6.1 source, but I don't have the time to do it.
I haven't used Zope in a long time.

**Comment by georgpfolz** [comment]
I think I'll do it :)

**Comment by georgpfolz** [comment]
I did it, Pull Request #5

**Comment by georgpfolz** [comment]
By the way, the browse tab is awesome, especially the fact that it displays the creation string of a table. I use it a lot in my daily work.
