### ISSUE TITLE
Missing ZSQLiteDA/images

### ISSUE THREAD

**Issue by tech-kio** [nakagami/Products.ZSQLiteDA#8]
When we try to install in latest Zope 5 we get:
  File "eggs/Products.ZSQLiteDA-0.7.2-py3.7.egg/Products/ZSQLiteDA/__init__.py", line 16, in <module>
    misc_={'conn': ImageFile('images/DBAdapterFolder_icon.gif', globals()),

Folder ZSQLiteDA/images is missing as well as these images:
DBAdapterFolder_icon.gif
table.gif

Thanks!

**Comment by georgpfolz** [comment]
Here are the images!

[images.tar.gz](https://github.com/nakagami/Products.ZSQLiteDA/files/8549650/images.tar.gz)

**Comment by nakagami** [comment]
gif image not in tarball
I'll check later.

**Comment by georgpfolz** [comment]
I just downloaded it and checked, there are 2 gif images in the tarball:

- DBAdapterFolder_icon.gif
- table.gif

**Comment by nakagami** [comment]
download from here
https://pypi.org/project/Products.ZSQLiteDA/#files

extract tarball and I can't find images
```
tar ztvf Products.ZSQLiteDA-0.7.3.tar.gz 
```

Please wait a moment while we release 0.7.4

**Comment by tech-kio** [comment]
Hey it works!

finally can get rid of my "custom" version and use buildout proper.

You can close.


Thanks very much!

**Comment by nakagami** [comment]
Thanks
